### ISSUE TITLE
微打赏跟微博监控好像有点问题

### ISSUE THREAD

**Issue by a541616013** [chinshin/qqbot_hzx#1]
wds可以出连接跟前20，但是刚刚jz完的人不能出来。微博更新也收不到。。

**Comment by chinshin** [comment]
- [x]  **issue1:**   wds可以出连接跟前20，但是刚刚jz完的人不能出来。


Answer：沟通测试之后发现问题是使用者wds查询频率过快（不建议快于一分钟一次），返回数据会缺失。


--------------------------
 - [x]  **issue2:**   微博更新收不到。


Answer：代码问题，已经修正。旧版`weibo.py`中只会初始查询一次，`start.py`调用方法后返回的都是初始查询数据；


修改后，将查询写入init()方法，每次调用都会获取最新微博数据；


经过实际测试，微博查询现在可以正常工作，机器人可以播报微博更新了。
